Crea un array_1 lleno ceros con una longitud de 8 elementos.
Haz que todos los elementos de este array sean igual a 2
Crea un array_2 que contenga todos los números pares del 1 al 10.
Suma todos los elementos del array_2 usando un bucle y después usando un método
de numpy. Compara los resultados
Revierte array_2 y guárdalo en una variable independiente.
Encuentra los elementos comunes entre array_1 y array_2 y entre array_2 y
array_2_revertido
(Pista: Investiga el uso de intersect1d() de numpy)
Crea un arrays lleno de 1s con una longitud dada por el usuario

In [2]:
import numpy as np

In [3]:
array=np.zeros(8)
array

array([0., 0., 0., 0., 0., 0., 0., 0.])

In [4]:
array[:]=2
array

array([2., 2., 2., 2., 2., 2., 2., 2.])

In [6]:
array2=np.arange(2,10,2)
array2

array([2, 4, 6, 8])

In [9]:
suma=0
for numero in array2:
    suma+=numero
sumanp=sum(array2)
sumanp

np.int64(20)

In [10]:
arrayRevertido=array2[::-1]
arrayRevertido

array([8, 6, 4, 2])

In [15]:
interseccion,indices_a,indices_b=np.intersect1d(arrayRevertido,array2,return_indices=True)
print(interseccion)
print(indices_b)
print(indices_a)

[2 4 6 8]
[0 1 2 3]
[3 2 1 0]


In [16]:
longitud=int(input('Introduce la longitud del array'))
arrayone=np.ones(longitud)
arrayone

array([1., 1., 1., 1., 1.])

Crea un array con 15 números enteros aleatorios entre 1 y 100
Multiplica todos los elementos del array usando un bucle y después usando un
método de numpy. Compara los resultados


In [16]:
arrayRandom=np.random.randint(1,101,size=15)
arrayRandom

array([11, 97, 82, 43, 87, 68, 60, 41, 81,  9, 75, 11, 84, 55, 50])

In [6]:
resultado=1
for numero in arrayRandom:
    resultado*=numero
resultado

np.int64(1403136)

In [7]:
resultadoArray=np.prod(arrayRandom)
resultado

np.int64(1403136)

Crea otro array con 15 números decimales aleatorios entre 0 y 1
Suma los elementos de ambos arrays elementos por elemento. Resuélvelo usando un
operador y después con una función de numpy
(Pista: busca en google que función de numpy hace esto)
Ahora réstalos. Resuélvelo usando un operador y después con una función de numpy
(Pista: busca en google que función de numpy hace esto)

In [ ]:
arrayDecimal=np.random.random(15)
arrayDecimal

array([0.0788244 , 0.65977   , 0.85324647, 0.37318621, 0.72606885,
       0.77643333, 0.85121331, 0.64548067, 0.95160053, 0.22223034,
       0.63179892, 0.88299109, 0.71331604, 0.68742497, 0.54243065])

In [17]:
arraySuma=np.add(arrayRandom,arrayDecimal)
arraySuma

array([11.0788244 , 97.65977   , 82.85324647, 43.37318621, 87.72606885,
       68.77643333, 60.85121331, 41.64548067, 81.95160053,  9.22223034,
       75.63179892, 11.88299109, 84.71331604, 55.68742497, 50.54243065])

In [18]:
arrayResta=arrayRandom-arrayDecimal
arrayResta

array([10.9211756 , 96.34023   , 81.14675353, 42.62681379, 86.27393115,
       67.22356667, 59.14878669, 40.35451933, 80.04839947,  8.77776966,
       74.36820108, 10.11700891, 83.28668396, 54.31257503, 49.45756935])

In [21]:
arr=np.zeros(15)
for i in range(0,len(arrayRandom)):
    arr[i]=arrayRandom[i]*arrayDecimal[i]
arr

array([ 0.86706845, 63.99769026, 69.96621042, 16.04700722, 63.16799038,
       52.79746652, 51.07279838, 26.46470758, 77.07964326,  2.00007307,
       47.38491919,  9.71290195, 59.91854754, 37.80837345, 27.12153264])

Haz lo mismo con la multiplicación elemento por elemento. Usa un operador y
después con una función de numpy
(Pista: busca en google que función de numpy hace esto)
Encuentra el valor más alto del primer array que has creado.
Calcula la media (mean), la mediana (median) y al deviación estandar (standard
deviation) de los arrays (Nota: No nos importa el significado matemático de estos
valores, lo importante es que encuentres que función de numpy necesitas. Puedes
hacer la búsqueda en castellano o en inglés, aunque en inglés muchas veces suele
haber más resultados).

In [22]:
arrayMultiplicacion=(arrayRandom*arrayDecimal)
arrayMultiplicacion

array([ 0.86706845, 63.99769026, 69.96621042, 16.04700722, 63.16799038,
       52.79746652, 51.07279838, 26.46470758, 77.07964326,  2.00007307,
       47.38491919,  9.71290195, 59.91854754, 37.80837345, 27.12153264])

In [ ]:
maximo=np.max(arrayRandom)
maximo

np.float64(28.19566554553298)

Crea un arrays lleno de 1s con una longitud dada por el usuario
10.Cambia la forma del array para que tenga una estructura de tipo (filas, columnas)
11.Crea una “matriz identidad” con la misma forma que el array anterior (filas, columnas)
12.Concatena ambas estructuras horizontalmente y verticalmente
(Pista: Investiga el funcionamiento de concatenate() y de vstack() y hstack() de numpy)

In [35]:
array1=np.ones(9)
array1=array1.reshape(3,3)
array2=np.eye(3)
array2
arrayV=np.vstack((array1,array2))
arrayV
arrayH=np.hstack((array1,array2))
arrayH


array([[1., 1., 1., 1., 0., 0.],
       [1., 1., 1., 0., 1., 0.],
       [1., 1., 1., 0., 0., 1.]])