Supongamos que tienes un conjunto de datos de ventas de una tienda durante un año. 
Cada fila representa una venta y tiene tres columnas: la fecha de la venta, el monto de la 
venta y la categoría de producto vendido (por ejemplo, electrónicos, ropa, alimentos, 
etc.). Quieres analizar estos datos para determinar cuánto fue el monto total de ventas en 
cada mes. Para ello, puedes usar NumPy para cargar los datos en un array de 3 
columnas y n filas, donde n es el número de ventas. Luego, puedes usar operaciones de 
NumPy para filtrar los datos por mes y sumar los montos de venta correspondientes.

In [2]:
import numpy as np

In [3]:
ventas=np.array([
    ['2022-01-01',100,'ropa'],
    ['2022-01-02',200,'alimento'],
    ['2022-01-03',150,'ropa'],
    ['2022-02-01',120,'alimento'],
    ['2022-02-02',180,'electrodomesticos'],
    ['2022-02-03',200,'alimento'],
    ['2022-03-01',90,'ropa'],
    ['2022-03-02',110,'electrodomesticos'],
    ['2022-03-03',100,'alimento'],
])
ventas

array([['2022-01-01', '100', 'ropa'],
       ['2022-01-02', '200', 'alimento'],
       ['2022-01-03', '150', 'ropa'],
       ['2022-02-01', '120', 'alimento'],
       ['2022-02-02', '180', 'electrodomesticos'],
       ['2022-02-03', '200', 'alimento'],
       ['2022-03-01', '90', 'ropa'],
       ['2022-03-02', '110', 'electrodomesticos'],
       ['2022-03-03', '100', 'alimento']], dtype='<U21')

In [14]:
fechas=np.array([venta[0] for venta in ventas])
fechas

array(['2022-01-01', '2022-01-02', '2022-01-03', '2022-02-01',
       '2022-02-02', '2022-02-03', '2022-03-01', '2022-03-02',
       '2022-03-03'], dtype='<U10')

In [16]:
meses=np.array([int(fecha[5:7]) for fecha in fechas])
meses

array([1, 1, 1, 2, 2, 2, 3, 3, 3])

In [20]:
monto_mes=np.zeros(12)
for mes in range(1,13):
    ventasPorMes=ventas[meses==mes]
    monto_mes[mes-1]=np.sum(ventasPorMes[:,1].astype(int))
print(monto_mes)

[450. 500. 300.   0.   0.   0.   0.   0.   0.   0.   0.   0.]


In [3]:
clima=np.array([
    [20,70,1009,1],
    [21,60,1011,1],
    [22,40,1010,1],
    [18,75,1012,2],
    [21,60,1008,3],
    [22,65,1008,3],
    [25,60,1010,4],
    [27,49,1007,5],
    [29,50,1007,5],
    [28,51,1007,5],
    [30,45,1005,6],
    [10,30,1005,6],
    [32,40,1002,7],
    [33,35,1001,8],
    [31,45,1003,9],
    [30,42,1001,9],
    [29,42,1002,9],
    [35,43,1001,9],
    [28,50,1006,10],
    [25,59,1012,11],
    [27,58,1011,11],
    [24,70,1011,12],
])
clima

array([[  20,   70, 1009,    1],
       [  21,   60, 1011,    1],
       [  22,   40, 1010,    1],
       [  18,   75, 1012,    2],
       [  21,   60, 1008,    3],
       [  22,   65, 1008,    3],
       [  25,   60, 1010,    4],
       [  27,   49, 1007,    5],
       [  29,   50, 1007,    5],
       [  28,   51, 1007,    5],
       [  30,   45, 1005,    6],
       [  10,   30, 1005,    6],
       [  32,   40, 1002,    7],
       [  33,   35, 1001,    8],
       [  31,   45, 1003,    9],
       [  30,   42, 1001,    9],
       [  29,   42, 1002,    9],
       [  35,   43, 1001,    9],
       [  28,   50, 1006,   10],
       [  25,   59, 1012,   11],
       [  27,   58, 1011,   11],
       [  24,   70, 1011,   12]])

In [14]:
meses=clima[:,3]
valoresPromedioMes=np.zeros([12,3])
for mes in range(1,13):
    promedioMes=clima[meses==mes]
    valoresPromedioMes[mes-1,0]=np.mean(promedioMes[:,0])
    valoresPromedioMes[mes-1,1]=np.mean(promedioMes[:,1])
    valoresPromedioMes[mes-1,2]=np.mean(promedioMes[:,2])
temperaturaMediaAnual=valoresPromedioMes.T[0]
humedadMediaAnual=valoresPromedioMes.T[1]
presionMediaAnual=valoresPromedioMes.T[2]
print(np.mean(temperaturaMediaAnual))
print(np.mean(humedadMediaAnual))
print(np.mean(presionMediaAnual))

    

25.645833333333332
53.18055555555555
1007.1041666666666
