Crea un array_1 lleno ceros con una longitud de 8 elementos.
Haz que todos los elementos de este array sean igual a 2
Crea un array_2 que contenga todos los números pares del 1 al 10.
Suma todos los elementos del array_2 usando un bucle y después usando un método
de numpy. Compara los resultados
Revierte array_2 y guárdalo en una variable independiente.
Encuentra los elementos comunes entre array_1 y array_2 y entre array_2 y
array_2_revertido
(Pista: Investiga el uso de intersect1d() de numpy)
Crea un arrays lleno de 1s con una longitud dada por el usuario

In [1]:
import numpy as np

In [3]:
array=np.zeros(8)
array

array([0., 0., 0., 0., 0., 0., 0., 0.])

In [4]:
array[:]=2
array

array([2., 2., 2., 2., 2., 2., 2., 2.])

In [6]:
array2=np.arange(2,10,2)
array2

array([2, 4, 6, 8])

In [9]:
suma=0
for numero in array2:
    suma+=numero
sumanp=sum(array2)
sumanp

np.int64(20)

In [10]:
arrayRevertido=array2[::-1]
arrayRevertido

array([8, 6, 4, 2])

In [15]:
interseccion,indices_a,indices_b=np.intersect1d(arrayRevertido,array2,return_indices=True)
print(interseccion)
print(indices_b)
print(indices_a)

[2 4 6 8]
[0 1 2 3]
[3 2 1 0]


In [16]:
longitud=int(input('Introduce la longitud del array'))
arrayone=np.ones(longitud)
arrayone

array([1., 1., 1., 1., 1.])